### ISSUE TITLE
Extension does not fire properly on some websites

### ISSUE THREAD

**Issue by fwenzel** [fwenzel/copy-shorturl#109]
From an add-on review:
```
Copy ShortURL stopped working for some websites, no matter which shortener you use. Tried "tinyurl.com", "bit.ly" and "is.gd".

Example website where it doesn't work:
"https://rdir.nl.wien.gv.at/form.do?agnCI=16&agnFN=Fullview&agnUID=nc.D.P4.Oj.BEH.BvQ.A.G4t0z_biNivj8qqGq4-QGtoEVVT7FbejDVz7pen4SxKsA9SWtLG0DzS2dsPUEVmF0KStCE3n4T8EEdIyttXHrw"

Pls fix it.```

**Comment by fwenzel** [comment]
Can confirm nothing shows up on the [Wien GV website](https://rdir.nl.wien.gv.at/form.do?agnCI=16&agnFN=Fullview&agnUID=nc.D.P4.Oj.BEH.BvQ.A.G4t0z_biNivj8qqGq4-QGtoEVVT7FbejDVz7pen4SxKsA9SWtLG0DzS2dsPUEVmF0KStCE3n4T8EEdIyttXHrw)

**Comment by fwenzel** [comment]
Bug found: On documents that do not have a `<title>` element, there will be an error.

**Comment by gsgolfer** [comment]
The problem still exists for me.  Doesn't work on FoxNews.com or https://www.golf-monthly.co.uk/

**Comment by fwenzel** [comment]
I cannot confirm this. Do you get an error in the browser console?

<img width="468" alt="image" src="https://user-images.githubusercontent.com/87232/77855700-f197f900-71a6-11ea-8a9b-5a0bf799076f.png">

**Comment by fwenzel** [comment]
I checked both sites you are highlighting and they work without problem.

**Comment by fwenzel** [comment]
Oh this is Firefox 74.

**Comment by fwenzel** [comment]
Why are you using a version 12 versions back?

**Comment by fwenzel** [comment]
Ah yes the latest versions do not work with older Firefox anymore. I will adjust the minimum versions.

**Comment by fwenzel** [comment]
I filed #111 to track minimum version question

**Comment by gsgolfer** [comment]
As a CEO over a tech company, I don't like the control Firefox is taking from users, and browser security hasen't improved that much.  I personally use Browsers for personal business but as a company, we use them for business as well.  Many clients can't or haven't upgraded websites to stay current with Mozilla's Firefox upgrade time line, it's too fast.  Consequently, many websites don't work properly with Firefox, the reason I went back to v62.  Also, past v62, Firefox progressively eliminates the users ability to control browser updating, some extensions quit working and websites get squirrely.  Your 5.0v works seamlessly with 62 and all sites, so I have uninstalled your latest, as it's erratic.  I have a Bitly account but it's too complex, but will use it if need be.  Hope the problem gets solved because I prefer your extension.

**Comment by fwenzel** [comment]
Sounds good thank you!

**Comment by gsgolfer** [comment]
Hello, just checking.. I went to look for your Copy ShortURL extension and it's not listed????

**Comment by fwenzel** [comment]
You can find older versions here: https://addons.mozilla.org/en-US/firefox/addon/copy-shorturl/versions/ hope this works!
