### ISSUE TITLE
Option to always use shortening service

### ISSUE THREAD

**Issue by stephenjudge** [fwenzel/copy-shorturl#21]
I like to follow the statistics of the URL's I creat with Bit.ly and so I would like all my short URL's to be created with Bit.ly. It would be nice to have an option in Copy ShortURL that allows you to ignore the canonical short URL provided but the website and always use the chosen shortening service.

**Comment by fwenzel** [comment]
I added a new setting, that defaults to 30 characters now.

The behavior is: If the site does not specify a *short* URL, then we send it to the shortening service regardless.

If the site specifies a URL that it considers *short*, then we send it to the shortening service if and only if it is longer than this threshold, which I arbitrarily set to 30 characters.

The functionality can be:
* disabled by setting the threshold to 0
* made to always kick in by setting it to less than 6 (because very URL has `http://` in it).
