### ISSUE TITLE
auto copy title along with short url

### ISSUE THREAD

**Issue by noman798** [fwenzel/copy-shorturl#66]
auto copy title when short url

**Comment by fwenzel** [comment]
Can you clarify what you're asking for? When clicking the button on a [news article](http://arstechnica.com/information-technology/2016/10/google-fiber-now-owns-a-wireless-isp-but-isnt-giving-up-on-fiber/), would you like to copy:

`Google Fiber is now a fiber and wireless ISP https://is.gd/ekWtWT`

instead of simply `https://is.gd/ekWtWT`?

That seems like it might be useful, but so I better understand: What's your use case?

**Comment by snowbound** [comment]
I would also like this option since I shorten URLs to either Tweet or paste in forrums or emails. This way people seeing the shortened URL will know automtically where the shortened URL goes to.

**Comment by fwenzel** [comment]
Sounds great. How do you suppose it should be formatted? URL first, then title?

**Comment by snowbound** [comment]
Well the extension I had been using in Firefox but which has since been deprecated in FF55 had the title of the current page title followed by the shortened URL. That way people knew what the link was going to.

**Comment by fwenzel** [comment]
Doable. Thank you
